
name: BoltGuard
main: com.tu_usuario.boltguard.BoltGuard
version: 1.0-SNAPSHOT
api-version: 1.8
commands:
  bgreload:
    description: Recarga config y checks.
    permission: boltguard.admin
  bginfo:
    description: Muestra información sobre BoltGuard.
    permission: boltguard.admin
  bgviolations:
    description: Muestra historial de detecciones.
    permission: boltguard.staff
permissions:
  boltguard.admin:
    default: op
  boltguard.staff:
    default: false
